# Generated by Django 5.1 on 2024-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CBSE_No", models.CharField(max_length=15, unique=True)),
                ("Name", models.CharField(max_length=100)),
                ("DOB", models.DateField()),
                ("Fathers_Name", models.CharField(max_length=100)),
                ("School_College_Class", models.CharField(max_length=100)),
                ("Home_Address", models.CharField(max_length=100)),
                ("Admit_Card_No", models.IntegerField()),
                ("Unit", models.CharField(max_length=50)),
                ("Rank", models.CharField(max_length=50)),
                ("Year_of_passing_B_Certificate", models.IntegerField()),
                ("Fresh_Failure", models.CharField(max_length=10)),
                ("Attendance_1st_year", models.IntegerField()),
                ("Attendance_2nd_year", models.IntegerField()),
                ("Attendance_3rd_year", models.IntegerField()),
                ("Name_of_camp_attended_1", models.CharField(max_length=100)),
                ("Date_camp_1", models.DateField()),
                ("Location_camp_1", models.CharField(max_length=100)),
                ("Name_of_camp_attended_2", models.CharField(max_length=100)),
                ("Date_camp_2", models.DateField()),
                ("Location_camp_2", models.CharField(max_length=100)),
                (
                    "Photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
            ],
        ),
    ]
