# Generated by Django 5.1 on 2024-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="DOB",
            field=models.CharField(max_length=20),
        ),
    ]
