# Generated by Django 5.1 on 2024-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_student_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Year_of_passing_B_Certificate",
            field=models.CharField(default="N/A", max_length=10),
        ),
    ]
