# Generated by Django 5.1 on 2024-08-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_student_attendance_1st_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Attendance_1st_year",
            field=models.IntegerField(default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Attendance_2nd_year",
            field=models.IntegerField(default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Attendance_3rd_year",
            field=models.IntegerField(default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Date_camp_1",
            field=models.DateField(default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Date_camp_2",
            field=models.DateField(default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Location_camp_1",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Location_camp_2",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Name_of_camp_attended_1",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Name_of_camp_attended_2",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
    ]
