# Generated by Django 5.1 on 2024-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_student_attendance_1st_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Attendance_1st_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Attendance_2nd_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Attendance_3rd_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Date_camp_1",
            field=models.CharField(default="N/A", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Date_camp_2",
            field=models.CharField(default="N/A", max_length=10, null=True),
        ),
    ]
