# Generated by Django 5.1 on 2024-08-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_student_attendance_1st_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admit_card_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="admit_card_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
