# Generated by Django 5.1 on 2024-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
