# Generated by Django 5.1 on 2024-08-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_brigadier_clerk_student_clerk_colonel_clerk_colonel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brigadier",
            name="Director_general",
        ),
        migrations.RemoveField(
            model_name="colonel",
            name="Brigadier",
        ),
        migrations.AlterField(
            model_name="clerk",
            name="colonel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clerks",
                to="home.colonel",
            ),
        ),
        migrations.AddField(
            model_name="brigadier",
            name="director_general",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brigadiers",
                to="home.director_general",
            ),
        ),
        migrations.AddField(
            model_name="colonel",
            name="brigadier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colonels",
                to="home.brigadier",
            ),
        ),
    ]
