# Generated by Django 5.1 on 2024-08-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_brigadier_director_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='brigadier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brigadier'),
        ),
        migrations.AddField(
            model_name='student',
            name='colonel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colonel'),
        ),
        migrations.AddField(
            model_name='student',
            name='director_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.director_general'),
        ),
    ]
