# Generated by Django 5.1 on 2024-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_brigadier_student_colonel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved_by_brigadier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_by_colonel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_by_director_general',
            field=models.BooleanField(default=False),
        ),
    ]
