# Generated by Django 5.1 on 2024-08-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='approved_by_brigadier',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approved_by_colonel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approved_by_director_general',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
