# Generated by Django 5.1 on 2024-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_student_sent_for_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admit_card_send_for_approval",
            field=models.BooleanField(default=False),
        ),
    ]
