# Generated by Django 5.1 on 2024-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_student_admit_card_send_for_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Certificate_type",
            field=models.CharField(default="N/A", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="Wing",
            field=models.CharField(default="N/A", max_length=10, null=True),
        ),
    ]
